import type { Metadata } from "next";
import { Inter, DM_Sans } from "next/font/google";
import "./globals.css";

import Navbar from '@/app/components/ui/Navbar/Navbar';

const inter = Inter({ subsets: ["latin"] });
const dm_sans = DM_Sans({
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: {
    template: "%s | Frontera Hacks 2024",
    default: "Frontera Hacks 2024",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dm_sans.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
